-- To display data on the number of visitor visits based on class year (2021), visit category, and provide a ranking (RANK) based on the total visits from largest to smallest with a focus on the class of 2021.
SELECT
	ANGKATAN,
	KATEGORI_KUNJUNGAN,
	SUM(JUMLAH_KUNJUNGAN) AS TOTAL_KUNJUNGAN,
	RANK() OVER (PARTITION BY ANGKATAN ORDER BY SUM(JUMLAH_KUNJUNGAN) DESC) AS PERINGKAT
FROM (
  SELECT
     A.ANGKATAN,
     KK.KATEGORI_KUNJUNGAN,
     SUM(F.JUMLAH) AS JUMLAH_KUNJUNGAN
  FROM
  	WAKTU AS W, 
  	ANGKATAN AS A, 
  	KATEGORI_KUNJUNGAN AS KK, 
  	FAKTA_PENGUNJUNG AS F
  WHERE W.ID_WAKTU = F.ID_WAKTU
  AND A.ID_ANGKATAN = F.ID_ANGKATAN
  AND KK.ID_KATEGORI = F.ID_KATEGORI
  AND A.ANGKATAN = 2021
  GROUP BY A.ANGKATAN, KK.KATEGORI_KUNJUNGAN
) AS SUBQUERY
GROUP BY ANGKATAN, KATEGORI_KUNJUNGAN
ORDER BY ANGKATAN, TOTAL_KUNJUNGAN DESC;

-- To display the numbering in a data row that will start from 1 again if different batches, different months, for all visit categories, along with displaying the corresponding number of visits.
SELECT
  ROW_NUMBER() OVER (PARTITION BY BULAN, ANGKATAN ORDER BY JUMLAH_KUNJUNGAN DESC) AS NOMOR_URUT,
  BULAN,
  ANGKATAN,
  KATEGORI_KUNJUNGAN,
  JUMLAH_KUNJUNGAN
FROM (
  SELECT
    W.BULAN,
    A.ANGKATAN,
    KK.KATEGORI_KUNJUNGAN,
    SUM(F.JUMLAH) AS JUMLAH_KUNJUNGAN
  FROM 
    WAKTU AS W, 
    ANGKATAN AS A, 
    KATEGORI_KUNJUNGAN AS KK, 
    FAKTA_PENGUNJUNG AS F
  WHERE W.ID_WAKTU = F.ID_WAKTU
  AND A.ID_ANGKATAN = F.ID_ANGKATAN
  AND KK.ID_KATEGORI = F.ID_KATEGORI
  GROUP BY W.BULAN, A.ANGKATAN, KK.KATEGORI_KUNJUNGAN
) AS SUBQUERY
ORDER BY BULAN, ANGKATAN, JUMLAH_KUNJUNGAN DESC;

-- To display the aggregated number of visits by month, batch, and specific visit category ('SERING').
SELECT BULAN, ANGKATAN, SUM(JUMLAH) AS JUMLAH_TOTAL
FROM WAKTU AS W, LOKASI AS L, ANGKATAN AS A, KATEGORI_KUNJUNGAN AS KK, FAKTA_PENGUNJUNG AS F
WHERE W.ID_WAKTU = F.ID_WAKTU
AND L.ID_LOKASI = F.ID_LOKASI
AND A.ID_ANGKATAN = F.ID_ANGKATAN
AND KK.ID_KATEGORI = F.ID_KATEGORI
AND KATEGORI_KUNJUNGAN = 'SERING'
GROUP BY ROLLUP (BULAN, ANGKATAN)
ORDER BY BULAN, JUMLAH_TOTAL DESC;

-- To display the total number of visitor visits by city ('Probolinggo' and 'Mojokerto'), month, and specific visit category ('SERING') for the 2021 cohort.
SELECT KOTA, BULAN, SUM(F.JUMLAH) AS JUMLAH_TOTAL
FROM WAKTU AS W, LOKASI AS L, ANGKATAN AS A, KATEGORI_KUNJUNGAN AS KK, FAKTA_PENGUNJUNG AS F
WHERE L.ID_LOKASI = F.ID_LOKASI
AND W.ID_WAKTU = F.ID_WAKTU
AND A.ID_ANGKATAN = F.ID_ANGKATAN
AND KK.ID_KATEGORI = F.ID_KATEGORI
AND ANGKATAN = 2021
AND KATEGORI_KUNJUNGAN = 'SERING'
AND (KOTA = 'Probolinggo' OR KOTA = 'Mojokerto')
GROUP BY CUBE (KOTA, BULAN)
ORDER BY JUMLAH_TOTAL DESC;
